<a href="https://colab.research.google.com/github/saptarshidas219/00-rahul/blob/master/olympic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
def load_data():

    import kagglehub
    from kagglehub import KaggleDatasetAdapter
    file_path = "athlete_events.csv"


    df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,"heesoo37/120-years-of-olympic-history-athletes-and-results",file_path,)

    df['Medal'] = df['Medal'].fillna('No Medal')
    df['Age'] = round(df['Age'].fillna(df['Age'].mean()))
    df['Height'] = round(df['Height'].fillna(df['Height'].mean()))
    df['Weight'] = round(df['Weight'].fillna(df['Weight'].mean()))


    dtype_map = {'ID':'int64', 'Name':'string', 'Sex':'category', 'Age':'float64', 'Height':'float64','Weight':'float64', 'Team':'string', 'NOC':'string', 'Games':'string',
                 'Year':'string', 'Season':'string', 'City':'string', 'Sport':'string', 'Event':'string','Medal':'category'}
    df = df.astype(dtype_map)


    return df

In [35]:
s = load_data()

/tmp/ipykernel_12210/3156633639.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,"heesoo37/120-years-of-olympic-history-athletes-and-results",file_path,)

Using Colab cache for faster access to the '120-years-of-olympic-history-athletes-and-results' dataset.

In [36]:
s.head(3)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No Medal
2,3,Gunnar Nielsen Aaby,M,24.0,175.0,71.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,No Medal

In [37]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  string
 2   Sex     271116 non-null  category
 3   Age     271116 non-null  float64
 4   Height  271116 non-null  float64
 5   Weight  271116 non-null  float64
 6   Team    271116 non-null  string
 7   NOC     271116 non-null  string
 8   Games   271116 non-null  string
 9   Year    271116 non-null  string
 10  Season  271116 non-null  string
 11  City    271116 non-null  string
 12  Sport   271116 non-null  string
 13  Event   271116 non-null  string
 14  Medal   271116 non-null  category
dtypes: category(2), float64(3), int64(1), string(9)
memory usage: 27.4 MB

In [92]:
df_india = s[(s['Team']=='India')].copy()
df_india = df_india.reset_index()
df_india = df_india.drop(columns=['index'])

In [93]:
df_indiaMedal=df_india[['Year','Sport','Medal']]

In [94]:
df_indiaMedal['Count'] = 1

/tmp/ipykernel_12210/3200282638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indiaMedal['Count'] = 1

In [95]:
df_indiaMedal=df_indiaMedal.pivot_table(index = 'Year',columns='Medal',values='Count',aggfunc='sum',fill_value=0)

/tmp/ipykernel_12210/600255421.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_indiaMedal=df_indiaMedal.pivot_table(index = 'Year',columns='Medal',values='Count',aggfunc='sum',fill_value=0)

In [96]:
df_indiaMedal

Medal  Bronze  Gold  No Medal  Silver
Year
1900        0     0         3       2
1920        0     0         7       0
1924        0     7        20       0
1928        0    14        10       0
1932        0    15        11       0
1936        0    19        11       0
1948        0    20        69       0
1952        1    14        79       0
1956        0    17        62       0
1960        0     0        36      13
1964        0    15        97       0
1968       16     0        14       0
1972       14     0        29       0
1976        0     0        26       0
1980        0    16        62       0
1984        0     0        53       0
1988        0     0        58       0
1992        0     0        65       0
1996        1     0        53       0
1998        0     0         1       0
2000        1     0        69       0
2002        0     0         1       0
2004        0     0        80       1
2006        0     0         5       0
2008        2     1        64       0
2010        0     0         3       0
2012        4     0        85       2
2014        0     0         2       0
2016        1     0       128       1